### ISSUE TITLE
missing selective_scan_interface.py

### ISSUE THREAD

**Issue by uldyssian2008** [Cranial-XIX/longhorn#1]
hi thanks for sharing the code; however, i couldnt run the code sicne selective_scan_interface.py is missing.
How do I run the code?

**Comment by Cranial-XIX** [comment]
Hi, the Cuda kernels are kept in a separate repo in case people need that but not the training pipeline. The repo is listed in the README, which is `git clone https://github.com/Cranial-XIX/longhorn_cuda.git` You can follow the instructions in README to install it.

**Comment by uldyssian2008** [comment]
> Hi, the Cuda kernels are kept in a separate repo in case people need that but not the training pipeline. The repo is listed in the README, which is `git clone https://github.com/Cranial-XIX/longhorn_cuda.git` You can follow the instructions in README to install it.

thank you!
